# basic options
title: Deveb 0.1
author: deveb
email: your-email@domain.com
description: Bu proje CSS'nin tüm imkanlarını zorlayarak daha gelişmiş bir önyüz iskeleti oluşturmak için geliştirilmektedir.
twitter_username: datadeveb
github_username:  data-deveb

# Build settings
markdown: kramdown
theme: minima

# Açık bağlar
basla: /belgeler/basla.html
onbakis: /belgeler/basla/onbakis.html
belgeler: /belgeler/index.html
belgeler_kurulum: /belgeler/2.0/kurulum.html
belgeler_bakis: /belgeler/2.0/bakis.html
belgeler_giris: /belgeler/2.0/giris.html
belgeler_ogretici1: /belgeler/2.0/ogretici1.html

# Ders bağları
dersler_onbakis: /diger.html
